### ISSUE TITLE
Language not switching

### ISSUE THREAD

**Issue by mehdibo** [bkader/ci-gettext-hook#2]
I'm under a development environment (all errors appear no need for logs).

In a testing controller I have the following code:

```
var_dump(switch_language('ar'),  client_language(), current_language());
echo line('Welcome to CodeIgniter');
```

I get the following output:
switch_language('ar') is TRUE.
client_language() is English (an array)
current_language() is Englisn (same array)

The lang cookie is set to arabic (I think the problem is that I have a prefix, I'm not sure)

BTW where is the `$CFG` declared?

**Comment by bkader** [comment]
I don't think the cookie prefix is the issue. Can you please check your logs?  
**$CFG** and **$IN** are both declared in **system/core/CodeIgniter.php** .. They are instances of **Config** and **Input** classes.

**Comment by mehdibo** [comment]
Well unfortunately I think the prefix is the issue, I removed the cookie prefix and now it works.
I enabled the logs just to be sure, no errors. I'm 90% sure it's the cookie prefix

**Comment by mehdibo** [comment]
**UPDATE**
It is the cookie_prefix, you are using the `cookie` method from the `input` class.
Which does not add the prefix automatically.
From the Documentation:

> Unlike the Cookie Helper function get_cookie(), this method does NOT prepend your configured $config['cookie_prefix'] value.

**Comment by bkader** [comment]
I see. Can you open **application/hooks/gettext/Gettext.php** and add the following line around line **106** (below the **if** that returns void):  

    if ( ! empty($this->config['cookie']))
    {
        $this->config['cookie'] = config_item('cookie_prefix').str_replace(config_item('cookie_prefix'), '', $this->config['cookie']);
    }

**Comment by mehdibo** [comment]
Are you sure it's line 6? Line 6 is a comment

**Comment by bkader** [comment]
I fixed the comment, it's line **106** ! Sorry. Right before that line. I updated the class on github, I hope that solves the issue.

**Comment by mehdibo** [comment]
I tried and it didn't fix the problem and I don't think it's the proper way to fix it, do you have like a a Facebook or Twitter? something with instant messaging I'd like to suggest a fix

**Comment by bkader** [comment]
Sure: [Facebook](https://fb.me/666bits) and [Twitter](https://twitter.com/KaderBouyakoub).
